<aside class="sidebar articles-index left">
    <section class=article-group>
        <h6 class="group-title padded-title">1930 &ndash; 1949</h6>
        <ul class=group-list>
            <li><a href="#" title="The Nazis" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">The Nazis</a></li>
            <li><a href="#" title="Denmark 1943" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Denmark 1943</a></li>
            <li><a href="#" title="Japanese Internment Camps" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Japanese Internment Camps</a></li>
            <li><a href="#" title="Tuskegee Experiment" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Tuskegee Experiment</a></li>
            <li><a href="#" title="Jackie Robinson" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Jackie Robinson</a></li>
        </ul>
    </section>
    <section class=article-group>
        <h6 class="group-title padded-title">1930 &ndash; 1949</h6>
        <ul class=group-list>
            <li><a href="#" title="The Nazis" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">The Nazis</a></li>
            <li><a href="#" title="Denmark 1943" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Denmark 1943</a></li>
            <li><a href="#" title="Japanese Internment Camps" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Japanese Internment Camps</a></li>
            <li><a href="#" title="Tuskegee Experiment" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Tuskegee Experiment</a></li>
            <li><a href="#" title="Jackie Robinson" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Jackie Robinson</a></li>
        </ul>
    </section>
    <section class=article-group>
        <h6 class="group-title padded-title">1930 &ndash; 1949</h6>
        <ul class=group-list>
            <li><a href="#" title="The Nazis" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">The Nazis</a></li>
            <li><a href="#" title="Denmark 1943" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Denmark 1943</a></li>
            <li><a href="#" title="Japanese Internment Camps" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Japanese Internment Camps</a></li>
            <li><a href="#" title="Tuskegee Experiment" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Tuskegee Experiment</a></li>
            <li><a href="#" title="Jackie Robinson" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Jackie Robinson</a></li>
        </ul>
    </section>
    <section class=article-group>
        <h6 class="group-title padded-title">1930 &ndash; 1949</h6>
        <ul class=group-list>
            <li><a href="#" title="The Nazis" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">The Nazis</a></li>
            <li><a href="#" title="Denmark 1943" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Denmark 1943</a></li>
            <li><a href="#" title="Japanese Internment Camps" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Japanese Internment Camps</a></li>
            <li><a href="#" title="Tuskegee Experiment" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Tuskegee Experiment</a></li>
            <li><a href="#" title="Jackie Robinson" data-excerpt="On October 23, 1989 Charles and Carol Stuart left their childbirth class in Boston. Carol Stuart was murdered that night, and the terrible events that followed were like something out of a Hitchcock mystery. Unfortunately racial tensions still present in our society caused the investigation to veer so far from the truth that a black man was nearly framed for the perfect murder">Jackie Robinson</a></li>
        </ul>
    </section>
</aside>